[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyiconeus"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "simoncampredon-lang", email = "simon.campredon@iconeus.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
"numpy",
"pytz",
"h5py",
"transforms3d",
"pytest",
]

[project.urls]
Documentation = "https://github.com/simoncampredon-lang/pyiconeus#readme"
Issues = "https://github.com/simoncampredon-lang/pyiconeus/issues"
Source = "https://github.com/simoncampredon-lang/pyiconeus"

[tool.hatch.version]
path = "src/pyiconeus/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/pyiconeus tests}"

[tool.coverage.run]
source_pkgs = ["pyiconeus", "tests"]
branch = true
parallel = true
omit = [
  "src/pyiconeus/__about__.py",
]

[tool.coverage.paths]
pyiconeus = ["src/pyiconeus", "*/pyiconeus/src/pyiconeus"]
tests = ["tests", "*/pyiconeus/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.mypy]
ignore_missing_imports = true


[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.hatch-test.scripts]
run = "pytest{env:HATCH_TEST_ARGS:} {args}"
run-cov = "coverage run -m pytest{env:HATCH_TEST_ARGS:} {args}"
cov-combine = "coverage combine"
cov-report = "coverage report"
