# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyIconeus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prepare-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Download test datas
      run: python download_script.py
    
    - name: Upload test datas
      uses: actions/upload-artifact@v4
      with:
        name: test-data-artifact
        path: tests/data/
        retention-days: 1

  build:
    needs: prepare-data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Download test datas artifact
      uses: actions/download-artifact@v4
      with:
        name: test-data-artifact
        path: tests/data/

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Hatch
      run: pipx install hatch
      
    - name: Run test
      run: hatch test
